version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: contenedor-mongo
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: 123Secret
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27017:27017"
